/**
 * Generated by tsnapi — public API snapshot of `dsh-elysia`
 */
// #region Interfaces
export interface HostContext<Options = undefined> {
  __host_instance: HostServiceInstance<Options>;
}
export interface HostServiceInstance<Options = undefined> {
  context: Context;
  options: Options;
}
// #endregion

// #region Types
export type HostApp<Options = undefined> = Elysia<'', {
  decorator: {
    __host_instance: HostServiceInstance<Options>;
  };
  store: Record<never, never>;
  derive: Record<never, never>;
  resolve: Record<never, never>;
}>;
export type HostService<Options = undefined> = (undefined extends Options ? (ctx: Context, options?: Options) => () => void : (ctx: Context, options: Options) => () => void) & {
  __host_instance?: HostServiceInstance<Options>;
};
// #endregion

// #region Functions
export declare function defineWebServer<Options = undefined>(_: (_: HostApp<Options>) => void | AnyElysia): HostService<Options>;
// #endregion