/**
 * Generated by tsnapi — public API snapshot of `dsh-elysia/utils`
 */
// #region Functions
export declare function getServerContext<Context$1 = Context>(_: HostService<any> | HostContext<unknown>): Context$1;
export declare function getServerOptions<Options>(_: HostService<Options> | HostContext<Options>): Options;
// #endregion